config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from diamoyeo.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('informations/', include('informations.urls', namespace = 'informations')),
    path('diamoyeo/', include('diamoyeo.urls', namespace = 'diamoyeo')),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('jobs/',include('jobs.urls',namespace = 'jobs')),
    path('', home_view, name='home'),
]

# 사용자가 추가한 프로필 이미지 저장을 위한 urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from .views import scrap_view,identify_view, class_apply_view, jobs_creat_view, jobs_main_view, jobs_teacher_view, jobs_teacher_detail_view

app_name = 'jobs'

urlpatterns = [
    path('', jobs_main_view, name='jobs_main'),
    path('teacher/',jobs_teacher_view, name='teacher'),
    path('teacher/<int:id>/',jobs_teacher_detail_view, name='teacher_detail'),
    path('create/',jobs_creat_view, name='jobs_create'),
    path('create/certify/',identify_view, name='identify'), #인증
    path('apply/<int:id>/',class_apply_view, name = 'jobs_apply'),   #수업 신청서
    path('teacher/scrap/<int:bid>',scrap_view), #좋아요
]

posts/urls.py
from django.urls import path
from .views import post_list_view, post_create_view, post_detail_view, like_view,delete_comment

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name = 'post-list-all'),
    path('create/', post_create_view, name = 'post-create'),
    path('<int:id>/', post_detail_view , name = 'post-detail'),
    path('like/<int:bid>',like_view), #좋아요
    path('<int:id>/<int:comment_id>', delete_comment , name = 'comment_delete'),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()

CHOICES = (
    ('알바','알바'),
    ('과외','과외'),
    ('취준','취준'),
    ('경력단절','경력단절'),
    ('공지','공지'), # 운영자만 공지 글 작성 가능
    ('이벤트','이벤트'), #운영자만 공지 글 작성 가능
)

class Post(models.Model):
    title = models.TextField(verbose_name='제목',null=True, blank=True)
    category = models.CharField(max_length=20, choices=CHOICES, default='알바')
    writer = models.ForeignKey(to=User,on_delete=models.CASCADE,null=True,blank=True)
    image = models.ImageField(verbose_name = '이미지',null=True, blank=True)
    content = models.TextField(verbose_name = '내용')
    created_at = models.DateTimeField(verbose_name = '작성일',default=timezone.now)
    view_count = models.PositiveIntegerField(default=0, verbose_name='조회수')
    file = models.FileField(verbose_name = '파일',null=True, blank=True)
    like = models.ManyToManyField(User, related_name='likes',blank = True)
    
class Comment(models.Model):
    content = models.TextField(verbose_name = '내용')
    post = models.ForeignKey(to='Post',on_delete=models.CASCADE, null=True)
    writer = models.ForeignKey(to=User,on_delete=models.CASCADE,null=True, blank = True)
    created_at = models.DateTimeField(verbose_name='작성일',default = timezone.now)
    

posts/forms.py
from django import forms
from .models import Post, Comment

class PostBaseForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        
        
class PostCreateForm(PostBaseForm):
    CATEGORY_CHOICES = [
            ('알바','알바'),
            ('과외','과외'),
            ('취준','취준'),
            ('경력단절','경력단절'),
    ]
    category = forms.ChoiceField(label='카테고리',choices= CATEGORY_CHOICES)
    class Meta(PostBaseForm.Meta):
        fields = ['title', 'content', 'category']  
    
    def get_cleaned_data(self):
        cleaned_data = super().get_cleaned_data()
        cleaned_data['category'] = self.cleaned_data['category']
        return cleaned_data

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

posts/views.py
from django.shortcuts import render,redirect
from .models import Post,Comment
from .forms import PostCreateForm , CommentForm
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404
from datetime import datetime, timedelta
from itertools import chain
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

def post_list_view(request):
    
    if request.method=='GET':
        selected_category = request.GET.get('category')
        page = request.GET.get('page')
        
        if selected_category  is None:
            selected_category  = '전체'
        
        notice_list = Post.objects.filter(category = '공지').order_by('-created_at') #공지사항 글
        event_list = Post.objects.filter(category = '이벤트').order_by('-created_at')
        filter_list = Post.objects.exclude(writer__username = '관리자').order_by('-created_at') # 일반 사용자들 글
        
        if selected_category  == '전체': # 전체글 (완료)
            
            notice_list = notice_list[:5] # 공지 5개
            
            page_obj, paginator = make_page_obj(filter_list, page, 8) # 일반글 8개
            
            context = {
                'notice_list' : notice_list, # 공지글 5개
                'page_obj' : page_obj,
                'paginator' : paginator,
                'category' : selected_category,
            }
        elif selected_category == '공지': # 공지 글만 보이게 (완료)
            
            page_obj, paginator = make_page_obj(notice_list, page, 13)
            
            context = {
                'page_obj' : page_obj,
                'paginator' : paginator,
                'category' : selected_category,
            }
        elif selected_category == '이벤트': # 이벤트 글만 보이게 (완료)
            
            page_obj, paginator = make_page_obj(event_list, page, 13)
            
            context = {
                'page_obj' : page_obj,
                'paginator' : paginator,
                'category' : selected_category,
            }
            
        elif selected_category == '인기글': # 인기글만 보이게
            
            # 조회수가 0인 게시글 제외
            filter_list = filter_list.exclude(view_count=0).order_by('-view_count')
            
            page_obj, paginator = make_page_obj(filter_list, page, 13)
            
            context = {
                'post_list': filter_list,
                'page_obj' : page_obj,
                'paginator' : paginator,
                'category' : selected_category,
            }
            
        else: # 공지 5개, 선택된 카테고리에 해당하는 글 14개
            
            notice_list = notice_list[:5] # 공지 5개
            filter_list = filter_list.filter(category=selected_category) # 선택된 카테고리 글
            
            page_obj, paginator = make_page_obj(filter_list, page, 8)
            
            context = {
                'notice_list' : notice_list,
                'page_obj' : page_obj,
                'paginator' : paginator,
                'category' : selected_category,
            }
        return render(request,'posts/post-all.html',context)
    

def post_create_view(request):
    if request.method=='GET':
        form = PostCreateForm()
        context = {'form':form}
        return render(request, 'posts/post-create.html',context)
    elif request.method == 'POST':
        title = request.POST.get("post_title")
        content = request.POST.get("post_content")
        category = request.POST.get("align_mode")
        image = request.FILES.get("image")
        file = request.FILES.get("file")
        writer = request.user
        if image and file :
            post = Post.objects.create(
                title = title,
                content = content,
                writer = writer,
                category = category,
                image = image,
                file = file,
            )
        elif image :
            post = Post.objects.create(
                title = title,
                content = content,
                writer = writer,
                category = category,
                image = image,
            )
        elif file :
            post = Post.objects.create(
                title = title,
                content = content,
                writer = writer,
                category = category,
                file = file
            )
        else:
            post = Post.objects.create(
                title = title,
                content = content,
                writer = writer,
                category = category,
            )            
        return redirect('posts:post-list-all')
    else:
        return redirect('posts:post-list-all')

def post_detail_view(request, id):
    post = get_object_or_404(Post, id=id)
    comments = post.comment_set.all().order_by('-created_at')
    if request.method == 'GET':
        context = {
            'post': post,
            'commentForm': CommentForm(),
            'comments':comments,
        }

        # 쿠키
        cookie_name = f'cookie_{id}'
        if cookie_name not in request.COOKIES:
            post.view_count +=1
            post.save()
            
            expires = datetime.utcnow() + timedelta(seconds=30)  # 쿠키 만료 시간 (30초마다 쿠키 만료)
            expires = expires.strftime('%a, %d-%b-%Y %H:%M:%S GMT')
            response = HttpResponse(render(request, 'posts/post-detail.html',context))
            response.set_cookie(cookie_name, 'true', expires=expires)
            return response
        return render(request, 'posts/post-detail.html', context)
    if request.method =='POST':
        post = Post.objects.get(id=id)
        content = request.POST.get('comment_content')
        if content:
            comment = Comment.objects.create(
                content = content,
                post = post,
                writer = request.user,
            )
        else: 
            pass
        context = {
            'post':post,
        }
        return render(request,'posts/post-detail.html',context)
    return render(request,'post/post-detail.html')

def like_view(request, bid):
    post = get_object_or_404(Post, id=bid)
    user = request.user
    if post.like.filter(id =user.id).exists():
        post.like.remove(user)
        return JsonResponse({'message':'delete','like_count':post.like.count()})
    else:
        post.like.add(user)
        return JsonResponse({'message':'ok','like_count':post.like.count()})

# 만들 리스트, 현재 페이지, 한 페이지당 보여줄 포스트 개수
def make_page_obj(post_list, page, num_of_post,):
    paginator = Paginator(post_list, num_of_post)
    try:
        page_obj = paginator.page(page)
        return page_obj, paginator
    except PageNotAnInteger:
        page = 1
        page_obj = paginator.page(page)
        return page_obj, paginator
    except EmptyPage:
        page = paginator.num_pages
        page_obj = paginator.page(page)
        return page_obj, paginator

def delete_comment(request, id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('posts:post-detail', id=id)

templates/posts/post-all.html
{% extends 'base.html' %}
{% block title %}게시판{% endblock %}
{% load static %}
{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'css/screens/post-all.css' %}">
    <script defer src="{% static 'js/posts.js'%}"></script> 
    <style>
        .number-nav {
            width: 40%;
        }
        .no-underline {
            text-decoration: none;
        }
        .align_mode {
            margin-top: 30px;
        }
    </style>
</head>

<main class="posts-main">
    <div class="posts-main-content">
        <div class="main-left">
            <nav class="main-left__nav">
                <div class="main-left__nav-yellow"></div>
                <div class="main-left__nav-bookmark"></div>
                <div class="main-left__nav-white">
                    <img src="{% static 'image/main-logo.svg' %}">
                    <div class="main-left__nav-title"><span>Damo.yeo</span></div><div class="main-left__nav-border"></div>
                    <ul class="post-nav">
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=전체">전체글</a></li><div class="main-left__nav-border"></div>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=인기글">실시간 인기글</a> </li><div class="main-left__nav-border"></div>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=전체">게시판 모음</a></li><div class="main-left__nav-border"></div>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=알바">알바 게시판</a></li>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=과외">과외 게시판</a></li>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=취준">취준 게시판</a></li>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=경력단절">경력단절 게시판</a></li><div class="main-left__nav-border"></div>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=공지">공지사항</a></li><div class="main-left__nav-border"></div>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=이벤트">이벤트</a></li><div class="main-left__nav-border"></div>
                        
                    </ul>
                </div>
            </nav>
        </div>
        
        <div class="main-right">
            {% comment %} <button class="apply" onclick="location.href='{% url 'posts:post-create' %}'">작성하기</button> {% endcomment %}
            {% if category == '전체' %}
                <header class="main-right__title">전체글</header>
                <div class="main-right__column">
                    <div class="main-right__sub-title">모든 게시판의 글을 볼 수 있는 곳</div>
            {% elif category == '인기글' %}
                <header class="main-right__title">인기글</header>
                <div class="main-right__column">
                    <div class="main-right__sub-title">실시간으로 인기있는 글을 볼 수 있는 곳</div>
            {% elif category == '공지' %}
                <header class="main-right__title">공지사항</header>
                <div class="main-right__column">
                    <div class="main-right__sub-title">공지글을 볼 수 있는 곳</div>
            {% elif category == '알바' %}
                <header class="main-right__title">알바 게시판</header>
                <div class="main-right__column">
                    <div class="main-right__sub-title">알바와 관련된 글을 볼 수 있는 곳</div>
            {% elif category == '과외' %}
                <header class="main-right__title">과외 게시판</header>
                <div class="main-right__column">
                    <div class="main-right__sub-title">과외와 관련된 글을 볼 수 있는 곳</div>
            {% elif category == '취준' %}
                <header class="main-right__title">취준 게시판</header>
                <div class="main-right__column">
                    <div class="main-right__sub-title">취준과 관련된 글을 볼 수 있는 곳</div>
            {% elif category == '경력단절' %}
                <header class="main-right__title">경력단절 게시판</header>
                <div class="main-right__column">
                    <div class="main-right__sub-title">경력단절과 관련된 글을 볼 수 있는 곳</div>
            {% elif category == '이벤트' %}
                <header class="main-right__title">이벤트</header>
                <div class="main-right__column">
                    <div class="main-right__sub-title">이벤트와 관련된 글을 볼 수 있는 곳</div>
            {% endif %}
            <button class="apply" onclick="location.href='{% url 'posts:post-create' %}'"><img src="{% static 'image/edit-3.svg' %}"></button>
            </div>
            <div class="main-right__hr main-right__hr--bolder"></div>
            <form action="/informations/region/" method="GET" id="align_mode_form" class="align_mode_form">
                <select name="align_mode" id="align_mode" class="align_mode">
                    <option value="recently">최신순</option>
                    <option value="scrap">인기순</option>
                </select>
            </form>


            <section class="main-right__posts">
                <table class="posts-wrap">
                    <tr class="posts-wrap__top">
                        <td class="posts-wrap__topic posts-wrap__topic--top">Topic</th>
                        <th class="posts-wrap__title posts-wrap__title--top">제목</th>
                        <th class="posts-wrap__writer posts-wrap__writer--top">작성자</th>
                        <th class="posts-wrap__date posts-wrap__date--top">작성일</th>
                        <th class="posts-wrap__count posts-wrap__count--top">조회</th>
                    </tr>
                    {% if category == '공지' or category == '이벤트' or category == '인기글'%}
                        {% for post in page_obj %}
                            <tr class="posts-wrap__worry">
                                {% if category == '공지' %}
                                    <td class="posts-wrap__topic"><div class="posts-wrap__topic--notice">{{ post.category }}</div></td>
                                {% else %}
                                    <td class="posts-wrap__topic"><span class="posts-wrap__topic--worry">{{ post.category }}</span></td>
                                {% endif %}
                                <td class="posts-wrap__title posts-wrap__title--data"> <a href="{% url 'posts:post-detail' post.id %}" class = "no-underline">{{ post.title|truncatechars:44 }}</a></td>
                                <td class="posts-wrap__writer posts-wrap__writer--data">{{ post.writer }}</td>
                                <td class="posts-wrap__date posts-wrap__date--data">{{ post.created_at|date:"Y.m.d" }}</td>
                                <td class="posts-wrap__count posts-wrap__count--data">{{ post.view_count }}</td>
                            </tr>
                        {% endfor %}
                    {% else %} 

                        {% for post in notice_list %}
                            <tr class="posts-wrap__notice">
                                <td class="posts-wrap__topic"><div class="posts-wrap__topic--notice">{{ post.category }}</div></td>
                                <td class="posts-wrap__title posts-wrap__title--data"><a href="{% url 'posts:post-detail' post.id %}" class = "no-underline">{{ post.title|truncatechars:44 }}</td>
                                <td class="posts-wrap__writer posts-wrap__writer--data">{{ post.writer }}</td>
                                <td class="posts-wrap__date posts-wrap__date--data">{{ post.created_at|date:"Y.m.d" }}</td>
                                <td class="posts-wrap__count posts-wrap__count--data">{{ post.view_count }}</td>
                            </tr>
                        {% endfor %}

                        {% for post in page_obj %}
                        {% if post.category != '공지' %}
                            <tr class="posts-wrap__worry">
                                <td class="posts-wrap__topic"><span class="posts-wrap__topic--worry">{{ post.category }}</span></td>
                                <td class="posts-wrap__title posts-wrap__title--data"><a href="{% url 'posts:post-detail' post.id %}" class = "no-underline">{{ post.title|truncatechars:44 }}</td>
                                <td class="posts-wrap__writer posts-wrap__writer--data">{{ post.writer }}</td>
                                <td class="posts-wrap__date posts-wrap__date--data">{{ post.created_at|date:"Y.m.d" }}</td>
                                <td class="posts-wrap__count posts-wrap__count--data">{{ post.view_count }}</td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                
                </table>
            </section>
            {% comment %} pagination 관련 코드 {% endcomment %}
            <div class="posts-footer">
                {% if page_obj.has_other_pages %}
                    <ul class="number-nav">
                            {% if page_obj.has_previous %}
                                <li class="number-nav__list"><a href="?category={{category}}&page={{page_obj.previous_page_number}}"><img id="left-btn" src="{% static 'image/left-btn.svg' %}"></a></li>
                            {% endif %}

                            {% for page in paginator.page_range %}
                                {% if page == page_obj.number %}
                                    <li class="number-nav__list"><a href="?category={{category}}&page={{page}}">{{ page }}</a></li>    
                                {% else %}
                                    <li class="number-nav__list" style="color:#977F6A;" ><a href="?category={{category}}&page={{page}}">{{ page }}</a></li>    
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <li class="number-nav__list"><a href="?category={{category}}&page={{page_obj.next_page_number}}"><img id="right-btn" src="{% static 'image/left-btn.svg' %}"></a></li>
                            {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
</main>



{% endblock %}

templates/posts/post-create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}글쓰기{% endblock %}
{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'css/screens/post-create.css' %}">
</link>
</head>


<main class="posts-main">
    <div class="posts-main-content">
        <div class="main-left">
            <nav class="main-left__nav">
                <div class="main-left__nav-yellow"></div>
                <div class="main-left__nav-bookmark"></div>
                <div class="main-left__nav-white">
                    <img src="{% static 'image/main-logo.svg' %}">
                    <div class="main-left__nav-title"><span>Damo.yeo</span></div><div class="main-left__nav-border"></div>
                    <ul class="post-nav">
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=전체">전체글</a></li><div class="main-left__nav-border"></div>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=인기글">실시간 인기글</a> </li><div class="main-left__nav-border"></div>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=전체">게시판 모음</a></li><div class="main-left__nav-border"></div>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=알바">알바 게시판</a></li>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=과외">과외 게시판</a></li>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=취준">취준 게시판</a></li>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=경력단절">경력단절 게시판</a></li><div class="main-left__nav-border"></div>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=공지">공지사항</a></li><div class="main-left__nav-border"></div>
                        <li class="post-nav__list"><a href="{% url 'posts:post-list-all' %}?page=1&align_mode=recently&page=1&category=이벤트">이벤트</a></li><div class="main-left__nav-border"></div>
                        
                    </ul>
                </div>
            </nav>
        </div>
            <div class="main-right">
                <header class="main-right__title">글쓰기</header>
                <div class="main-right__hr main-right__hr--lighter"></div>

                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="main-right__choose-posts">
                        {% comment%}<form class="main-right__choose-posts-btn" action="/informations/region/" method="GET" id="align_mode_form" class="align_mode_form">{% endcomment %}
                            <div class = "main-right__choose-posts-btn">
                            <select name="align_mode" id="align_mode" class="align_mode--writing-page">
                                <option value="알바">게시판을 선택해 주세요.</option>
                                <option value="알바">알바 게시판</option>
                                <option value="과외">과외 게시판</option>
                                <option value="취준">취준 게시판</option>
                                <option value="경력단절">경력단절 게시판</option>
                            </select>
                            </div>
                        {% comment %} </form>{% endcomment %}

                    </div>
                    <div class="main-right__input-title">
                        {% comment %} <form class="main-right__input-title-form">{% endcomment %}
                            <div class = "main-right__input-title-form">
                            <input type="text" name="post_title" placeholder="제목을 입력해 주세요.">
                            </div>
                        {% comment %} <</form>{% endcomment %}
                    </div>
                
                    <div class="main-right__editor">
                        <label for="btn-image" class="editor-top editor-top-image">
                            <div><input type="file" name="image" id="btn-image" style="display: none;"></div>
                            <img height="34px" src="../../static/image/image.svg">
                            <span>사진</span>
                        </label>
                        <label for="btn-video" class="editor-top editor-top-video">
                            <div><input type="file" name="file" id="btn-video" style="display: none;"></div>
                            <img src="../../static/image/video.svg">
                            <span>동영상</span>
                        </label>
                        {%comment%}
                        <button id="btn-file" class="editor-top editor-top-file">
                            <img height="34px" src="../../static/image/file.svg">
                            <span>파일</span>
                        </button>
                        {%endcomment%}
                        {% comment %}
                        <button id="btn-save" class="editor-top editor-top-save">
                            <img src="../../static/image/save.svg">
                            <span>저장하기</span>
                        </button>
                        {% endcomment %}
                    </div>
                    <div>
                        <input type="text" class="textarea" name="post_content" class="main-right__input-text" contenteditable="true"></div>
                    </div>
                    {% comment%} <form class="save-form" style="background-color: antiquewhite;">
                        {% comment%}<input type="button" value="저장하기">
                    </form>
                    {% endcomment%}

                <div class = "save-form" style="background-color: antiquewhite;">
                    <button type="submit" value="저장하기"> 저장하기 </button>
                </div>

                </div>
            </form>
            </div>
        </div>
    </main>










{% endblock %}

templates/posts/게시글 상세페이지.html
{% extends 'base.html' %}
{% block title %}게시판 상세보기 페이지{% endblock %}
{% load static%}
{% block content %}

<h1>상세보기 페이지</h1>
<hr>
<div> 
    <h3>{{ post.title }}</h3>
    {% if post.category == '공지' %}
    <h4>공지사항 게시판</h4>
    {% elif post.category == '이벤트' %}
    <h4>이벤트 게시판</h4>
    {% else %}
    <h4>고민상담 > {{post.category}} 게시판 </h4>
    {% endif %}
    <hr>
    {% if post.writer.image %}
    <img src="{{ post.writer.image.url }}" alt="프로필 이미지">
    작성자 : {{post.writer}}
    {% else %}
    작성자 : {{post.writer}}
    {% endif %}
    
    <br>
    {{post.content}}
    <hr>
    
    {% comment %} 좋아요 비동기 {% endcomment %}
    좋아요
    {% if request.user in post.like.all %}
    <div onclick="sendRequest({{post.id}}, this)">♥{{ post.like.all.count }}</div>
    {% else %}
    <div onclick="sendRequest({{post.id}}, this)">♡{{ post.like.all.count }}</div>
    {% endif %}

    <script>
        function sendRequest(bid, event) {
            var httpRequest = new XMLHttpRequest();
            httpRequest.onreadystatechange = function () {
                if (httpRequest.readyState === XMLHttpRequest.DONE && httpRequest.status === 200) {
                    console.log(httpRequest.responseText);
    
                    var json_data = JSON.parse(httpRequest.responseText);
                    if (json_data['message'] === 'ok') {
                        event.innerText = "♥" + json_data['like_count'];
                    }else{
                        event.innerText = "♡" + json_data['like_count'];
                    }
                }
            };
            httpRequest.open("GET", "/posts/like/" + bid, true);
            httpRequest.send();
        }
    </script>



    {%comment%} 댓글 목록 {%endcomment%}
    {% for comment in post.comment_set.all %}
        <div>
            {% if comment.writer.image %}
                <img src="{{comment.writer.image.url}}"  height="40" width="40"> {{comment.writer}} 
            {% else %} 
                {{comment.writer}}
            {% endif %}
            {{ comment.content|linebreaksbr}}
        </div>
    {% endfor %}
    
    
    <hr>
    {% comment %} 댓글 달기 {% endcomment %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="comment_content" placeholder="댓글을 작성해주세요.">
        <button type="submit" onclick="location.href="{% url 'posts:post-detail' post.id %}"">완료</button>
    </form>

</div>
{% endblock %}