accounts/urls.py
from django.urls import path
from .views import signup_view, login_view, logout_view, mypage_view, activities_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name = 'signup'),
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('mypage/', mypage_view, name = 'mypage'),
    path('activities/', activities_view, name = 'activities'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from diamoyeo.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('informations/', include('informations.urls', namespace = 'informations')),
    path('diamoyeo/', include('diamoyeo.urls', namespace = 'diamoyeo')),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('jobs/',include('jobs.urls',namespace = 'jobs')),
    path('', home_view, name='home'),
]

# 사용자가 추가한 프로필 이미지 저장을 위한 urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

informations/urls.py
from django.urls import path
from .views import information_view, scrap, scrap_view_after,  scrap_view_region

app_name = 'informations'

urlpatterns = [
    path('scrap/after/<int:bid>', scrap_view_after , name = 'scrap'), # 스크랩 기능
    path('scrap/region/<int:bid>', scrap_view_region , name = 'scrap'), # 스크랩 기능
    path('', information_view, name = 'information'), # 탭에 따라 정보 보기
]

jobs/urls.py
from django.urls import path
from .views import scrap_view,identify_view, class_apply_view, jobs_creat_view, jobs_main_view, jobs_teacher_view, jobs_teacher_detail_view

app_name = 'jobs'

urlpatterns = [
    path('', jobs_main_view, name='jobs_main'),
    path('teacher/',jobs_teacher_view, name='teacher'),
    path('teacher/<int:id>/',jobs_teacher_detail_view, name='teacher_detail'),
    path('create/',jobs_creat_view, name='jobs_create'),
    path('create/certify/',identify_view, name='identify'), #인증
    path('apply/<int:id>/',class_apply_view, name = 'jobs_apply'),   #수업 신청서
    path('teacher/scrap/<int:bid>',scrap_view), #좋아요
]

posts/urls.py
from django.urls import path
from .views import post_list_view, post_create_view, post_detail_view, like_view,delete_comment

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name = 'post-list-all'),
    path('create/', post_create_view, name = 'post-create'),
    path('<int:id>/', post_detail_view , name = 'post-detail'),
    path('like/<int:bid>',like_view), #좋아요
    path('<int:id>/<int:comment_id>', delete_comment , name = 'comment_delete'),
]

jobs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()

class Class (models.Model):
    writer = models.ForeignKey(to=User,on_delete=models.CASCADE)
    name = models.TextField(verbose_name='이름') 
    image = models.ImageField(verbose_name = '프로필') 
    gender = models.TextField(verbose_name='성별') 
    age = models.IntegerField(verbose_name='나이') 
    school = models.TextField(verbose_name='학력') 
    cost = models.IntegerField(verbose_name='수업비용', default=10000) 
    times =models.TextField(verbose_name='시간대', null=True, blank=True) 
    info = models.TextField(verbose_name='강사정보',null=True, blank=True ) 
    student = models.TextField(verbose_name='수업 대상',null=True, blank=True) 
    feature = models.TextField(verbose_name='특이사항', null=True, blank=True) 
    group = models.TextField(verbose_name='수업분류', null=True, blank=True) 
    nationality = models.TextField(verbose_name='국적',null=True, blank=True)
    language = models.TextField(verbose_name='언어',null=True, blank=True)
    account = models.IntegerField(verbose_name='계좌번호', default=0,null=True, blank=True) 
    scrap = models.ManyToManyField(User, related_name='스크랩',blank = True)
    created_at = models.DateTimeField(verbose_name = '작성일',default=timezone.now)
    # 지불방식
    
class Register(models.Model):
    class_name = models.ForeignKey(to = 'Class', on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE,null=True, blank=True)
    student_name = models.TextField(verbose_name='이름') 
    student_age = models.IntegerField(verbose_name='나이')
    student_phone = models.CharField(verbose_name='전화번호',max_length=50)
    student_image = models.ImageField(verbose_name='프로필',null=True,blank = True)
    student_email = models.TextField(verbose_name='이메일')
    pay = models.TextField(verbose_name='지불방식')
    times =models.TextField(verbose_name='시간대', null=True, blank=True) 
    cost = models.IntegerField(verbose_name='수업비용', default=10000)
    created_at = models.DateTimeField(verbose_name = '등록일',default=timezone.now)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/footer.css' %}">
    <script src="{% static 'js/includeHTML.js' %}"></script>
    <title>{%block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div id="head">
            <div>
                <div onClick="location.href='{% url 'diamoyeo:home' %}'" style="cursor: pointer;"><img class="header-img" src="{% static 'image/로고.png' %}">다모여</div>
                <div id="divRight">
                    {% if request.user.is_authenticated %}
                        <div onClick="location.href='{% url 'accounts:mypage' %}'" style="cursor: pointer;"><img src="/static/image/basic.png">{{ request.user.username }}님ㅣ마이페이지</div>
                        <div class="div-div" onClick="location.href='{% url 'accounts:logout' %}'" style="cursor: pointer;">로그아웃</div>
                    {% else %}
                        <div onClick="location.href='{% url 'accounts:login' %}'" style="cursor: pointer;">로그인</div>|
                        <div onClick="location.href='{% url 'accounts:signup' %}'" style="cursor: pointer;">회원가입</div>
                    {% endif %}
                </div>
            </div>
        </div>    
        <div id="nav">
            <div>
                <div onClick="location.href='{% url 'diamoyeo:home' %}'" style="cursor: pointer;">메인</div>
                <div onClick="location.href='{% url 'jobs:jobs_main' %}'" style="cursor: pointer;">과외</div>
                <div onClick="location.href='{% url 'informations:information' %}?tab=region&align_mode=recently&page=1'" style="cursor: pointer;">지역정보</div>
                <div onClick="location.href='{% url 'posts:post-list-all' %}?page=1'" style="cursor: pointer;">게시판</div>
            </div>
        </div>
    </header>
    
    {% block content %}

    {% endblock %}

    <footer>
        <div style="font-size: 1rem; font-family: Inter; color: #FFF; font-weight: 600;"><img src="/static/image/하단 로고.png">DIAMO.YEA</div>
        <div style="font-size: 0.7rem; font-family: Inter;color: #FFF;">대표 : 멋쟁이 사자처럼 한성지부  Email : noname****</div>
        <div style="font-size: 0.7rem; font-family: Inter;color: #FFF;">대표번호: 02-760-4219  주소:서울특별시 성북구 삼선교로 16길 116</div>
    </footer>
</body>
</html>

templates/prac.html
{% extends 'base.html' %}
{% block title %}마이페이지{% endblock %}
{% load static %}
{% block content %}
<head>
    <style>
        .icon-container {
            display: flex;
        }
        
        .icon {
            text-align: center; /* 내부 요소들 가운데 정렬 */
            display: inline-block;
            margin-right: 20px;
        }
    </style>
    <script>
        var popup;

        function openPopup(argument) {
            // 팝업 창의 크기와 위치 설정
            var width = 1000;
            var height = 650;
            var left = (window.innerWidth - width) / 2;
            var top = (window.innerHeight - height) / 2;
        
            var url = "";

            if (argument === 'posts') {
                url = "{% url 'accounts:activities' %}?category=posts";
            } else if (argument === 'comments') {
                url = "{% url 'accounts:activities' %}?category=comments";
            } else if (argument === 'likes') {
                url = "{% url 'accounts:activities' %}?category=likes";
            } else if (argument === 'scraps') {
                url = "{% url 'accounts:activities' %}?category=scraps";
            }

             // Django 템플릿 태그를 이용하여 URL 생성

            popup = window.open(url, '새로운 팝업', 'width=' + width + ', height=' + height + ', left=' + left + ', top=' + top);

        }
        </script>
</head>
<h1>마이페이지</h1>
<hr>
[ 유저 정보 정상 출력 테스트 ] <br>
닉네임 : {{ request.user.username }} <br>
이메일 : {{ request.user.email }} <br>
소개 : {{ request.user.introduction }} <br>
{% if request.user.profile_image %}
    프로필 이미지 : <img class="mypage-img" src="{{ request.user.profile_image.url }}" width="50" height="50"><br>
{% else %}
    이미지 안넣음<br>
{% endif %}

인증 여부 : {{ request.user.is_verified }} <br>
<hr>
[ 수정 테스트 ]
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {% if request.user.profile_image %}
        <label for="id_image">이미지</label>
        기존 : {{ request.user.profile_image }}
        <input type="file" name="image" accept="image/*" id="id_image">
        {% else %}
        기존 : 이미지 안넣음
        <input type="file" name="image" accept="image/*" id="id_image">
        {% endif %}
    </div>
    <div>
        <label for="id_introduction">소개</label>
        <textarea name="introduction" id="introduction" cols="30" rows="10">{{ request.user.introduction }}</textarea>
    </div>
    <div>
        <input type="submit">
    </div>
</form>
<br>
<hr>
[ 계정 활동 ] <br>
<div class="icon-container">

    <a href="#" onclick="openPopup('posts')">
        <span class="icon">
            <br><img src="{% static 'image/post.png' %}" alt="내가 작성한 글"><br>작성글
        </span>
    </a>
    <a href="#" onclick="openPopup('comments')">
        <span class="icon">
            <br><img src="{% static 'image/comment.png' %}" alt="내가 작성한 댓글"><br>댓글
        </span>
    </a>
    <a href="#" onclick="openPopup('likes')">
        <span class="icon">
            <br><img src="{% static 'image/like.png' %}" alt="내가 좋아한 글"><br>좋아요
        </span>
    </a>
    <a href="#" onclick="openPopup('scraps')">
        <span class="icon">
            <br><img src="{% static 'image/scrap.png' %}" alt="내가 스크랩 한 글"><br>스크랩
        </span>
    </a>
</div>
{% endblock %}

    {% comment %} <a href="{% url 'accounts:activities' %}?category=posts"> {% endcomment %}
    {% comment %} <a href="{% url 'accounts:activities' %}?category=comments"> {% endcomment %}
    {% comment %} <a href="{% url 'accounts:activities' %}?category=likes"> {% endcomment %}
    {% comment %} <a href="{% url 'accounts:activities' %}?category=scraps"> {% endcomment %}