config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from diamoyeo.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('informations/', include('informations.urls', namespace = 'informations')),
    path('diamoyeo/', include('diamoyeo.urls', namespace = 'diamoyeo')),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('jobs/',include('jobs.urls',namespace = 'jobs')),
    path('', home_view, name='home'),
]

# 사용자가 추가한 프로필 이미지 저장을 위한 urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from .views import scrap_view,identify_view, class_apply_view, jobs_creat_view, jobs_main_view, jobs_teacher_view, jobs_teacher_detail_view

app_name = 'jobs'

urlpatterns = [
    path('', jobs_main_view, name='jobs_main'),
    path('teacher/',jobs_teacher_view, name='teacher'),
    path('teacher/<int:id>/',jobs_teacher_detail_view, name='teacher_detail'),
    path('create/',jobs_creat_view, name='jobs_create'),
    path('create/certify/',identify_view, name='identify'), #인증
    path('apply/<int:id>/',class_apply_view, name = 'jobs_apply'),   #수업 신청서
    path('teacher/scrap/<int:bid>',scrap_view), #좋아요
]

jobs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()

class Class (models.Model):
    writer = models.ForeignKey(to=User,on_delete=models.CASCADE)
    name = models.TextField(verbose_name='이름') 
    image = models.ImageField(verbose_name = '프로필') 
    gender = models.TextField(verbose_name='성별') 
    age = models.IntegerField(verbose_name='나이') 
    school = models.TextField(verbose_name='학력') 
    cost = models.IntegerField(verbose_name='수업비용', default=10000) 
    times =models.TextField(verbose_name='시간대', null=True, blank=True) 
    info = models.TextField(verbose_name='강사정보',null=True, blank=True ) 
    student = models.TextField(verbose_name='수업 대상',null=True, blank=True) 
    feature = models.TextField(verbose_name='특이사항', null=True, blank=True) 
    group = models.TextField(verbose_name='수업분류', null=True, blank=True) 
    nationality = models.TextField(verbose_name='국적',null=True, blank=True)
    language = models.TextField(verbose_name='언어',null=True, blank=True)
    account = models.IntegerField(verbose_name='계좌번호', default=0,null=True, blank=True) 
    scrap = models.ManyToManyField(User, related_name='스크랩',blank = True)
    created_at = models.DateTimeField(verbose_name = '작성일',default=timezone.now)
    # 지불방식
    
class Register(models.Model):
    class_name = models.ForeignKey(to = 'Class', on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE,null=True, blank=True)
    student_name = models.TextField(verbose_name='이름') 
    student_age = models.IntegerField(verbose_name='나이')
    student_phone = models.CharField(verbose_name='전화번호',max_length=50)
    student_image = models.ImageField(verbose_name='프로필',null=True,blank = True)
    student_email = models.TextField(verbose_name='이메일')
    pay = models.TextField(verbose_name='지불방식')
    times =models.TextField(verbose_name='시간대', null=True, blank=True) 
    cost = models.IntegerField(verbose_name='수업비용', default=10000)
    created_at = models.DateTimeField(verbose_name = '등록일',default=timezone.now)

jobs/forms.py
from django import forms
from .models import Class

class ClassBaseForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = '__all__'
        
class ClassCreateForm(ClassBaseForm):
    class Meta(ClassBaseForm.Meta):
        fields = '__all__'

jobs/views.py
from django.shortcuts import render,redirect
from .models import Class, Register
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
import json, random
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def jobs_main_view(request):
    if request.method == 'GET':
        teacher_list = Class.objects.all()
        random_teacher_list = random.sample(list(teacher_list), 6)

        context = {
            'teacher_list': random_teacher_list,

        }
        return render(request, 'jobs/jobs-all.html',context)
    return render(request, 'jobs/jobs-all.html')

def jobs_creat_view(request):
    if request.method == 'GET':
        return render(request, 'jobs/jobs-create.html')   
    elif request.method == 'POST':
        writer = request.user
        name = request.POST.get('named') #이름
        image = request.FILES.get('image') #프로필 사진
        gender = request.POST.get('gender') #성별
        age = request.POST.get('age') #나이
        school = request.POST.get('education')  #학력
        cost = int(request.POST.get('cost')) #비용
        info = request.POST.getlist('teacher') #강사정보
        student = request.POST.getlist('student')#수업대상
        feature = request.POST.get('feature')#특이사항
        group = request.POST.getlist('class') #수업 분류
        selected_cells = request.POST.get('selected_cells') #선택된 시간 (리스트형태)
        nationality = request.POST.get('nationality') #국적
        language = request.POST.get('language') #언어
        account = request.POST.get('pay') #계좌
        
        if selected_cells:
            selected_cells = json.loads(selected_cells)
        
        class_name = Class.objects.create(
            writer = writer,
            name=name,
            image = image,
            gender = gender,
            age=age,
            school = school,
            cost = cost,
            info = info,
            student = student,
            feature = feature,
            group = group,
            times = selected_cells,
            language = language,
            nationality = nationality,
            account = account,
        )
        return redirect('jobs:jobs_main')
    return render(request, 'jobs/jpbs-create.html')
        

# 선생님 전체 페이지
def jobs_teacher_view(request):
    
    page = request.GET.get('page')
    
    if request.method == 'GET':
        teacher_list = Class.objects.all().order_by('-created_at')
        
        page_obj, paginator = make_page_obj(teacher_list, page, 9)
        
        teacher_list1 = page_obj[:3]
        teacher_list2 = page_obj[3:6]
        teacher_list3 = page_obj[6:9]
        
        context = {
            'teacher_list':teacher_list,
            'teacher_list1':teacher_list1,
            'teacher_list2':teacher_list2,
            'teacher_list3':teacher_list3,
            'page_obj' : page_obj,
            'paginator' : paginator,
        }
        return render(request, 'jobs/jobs-teacher.html',context)
    return render(request, 'jobs/jobs-teacher.html',context)

#선생님 상세 페이지
def jobs_teacher_detail_view(request,id):
    teacher = get_object_or_404(Class, id=id)
    
    if request.method == 'GET':
        time_list = (teacher.times).split("'")
        info_list = (teacher.info).split("'")
        stu_list = (teacher.student).split("'")
        group_list = (teacher.group).split("'")
        remove_list = {', ','[',']'}
        time_lists = [i for i in time_list if i not in remove_list]
        time = len(time_lists)
        info_lists = [i for i in info_list if i not in remove_list]
        stu_lists = [i for i in stu_list if i not in remove_list]
        group_lists = [i for i in group_list if i not in remove_list]
        print(time_lists)
        context = {
            'teacher':teacher,
            'time_list':time_lists, #시간대
            'info_list':info_lists, #경력
            'stu_list':stu_lists,   #학생
            'group_list':group_lists, #수업 종류(비지니스, 유학 등)
            'time':time
            
        }
        return render(request, 'jobs/jobs-detail.html',context)
    
    return render(request, 'jobs/jobs-detail.html')

def class_apply_view(request, id):
    teacher = get_object_or_404(Class, id=id)
    if request.method == 'GET':
        time_lists = (teacher.times).split("'")
        remove_list = {', ','[',']'}
        time_lists = [i for i in time_lists if i not in remove_list]
        
        date_list9 = ['월9','화9','수9','목9','금9','토9','일9']
        date_list10 = ['월10','화10','수10','목10','금10','토10','일10']
        date_list11 = ['월11','화11','수11','목11','금11','토11','일11']
        date_list12 = ['월12','화12','수12','목12','금12','토12','일12']
        date_list13 = ['월13','화13','수13','목13','금13','토13','일13']
        date_list14 = ['월14','화14','수14','목14','금14','토14','일14']
        date_list15 = ['월15','화15','수15','목15','금15','토15','일15']
        date_list16 = ['월16','화16','수16','목16','금16','토16','일16']
        
        context = {
            'time_lists' : time_lists,
            'teacher':teacher,
            'date_list9':date_list9,
            'date_list10':date_list10,
            'date_list11':date_list11,
            'date_list12':date_list12,
            'date_list13':date_list13,
            'date_list14':date_list14,
            'date_list15':date_list15,
            'date_list16':date_list16,
        }
        return render(request, 'jobs/jobs-apply.html', context)
    elif request.method == 'POST':
        class_name = Class.objects.get(id=id)
        writer = request.user
        student_name = request.POST.get('name')
        student_age = request.POST.get('age')
        student_phone = request.POST.get('phone')
        student_email = request.POST.get('email')
        pay = request.POST.get('pays')
        student_image = request.FILES.get('image')
        times = request.POST.get('selected_cells') #선택된 시간 (리스트형태)

        if times:
            times = json.loads(times)
        #테스트용 출력
        print(times)
        cost = teacher.cost * len(times)
        
        if student_image :     # 수업 비용 추가해야 함
            Register.objects.create(
                class_name=class_name,
                writer = writer,
                student_name=student_name,
                student_age = student_age,
                student_phone = student_phone,
                student_image = student_image,
                student_email = student_email,
                pay = pay,
                times = times,
                cost = cost,
            )
        else:
            Register.objects.create(
                class_name=class_name,
                writer = writer,
                student_name=student_name,
                student_age = student_age,
                student_phone = student_phone,
                pay = pay,
                times = times,
                cost = cost,
            )
        return redirect('jobs:jobs_main')
    return render(request, 'jobs/jobs-apply.html', context)

def scrap_view(request, bid):
    teacher = get_object_or_404(Class, id=bid)
    user = request.user
    if teacher.scrap.filter(id =user.id).exists():
        teacher.scrap.remove(user)
        return JsonResponse({'message':'delete','like_count':teacher.scrap.count()})
    else:
        teacher.scrap.add(user)
        return JsonResponse({'message':'ok','like_count':teacher.scrap.count()})


def identify_view(request):
    return render(request,'jobs/jobs-certify.html' )

# 만들 리스트, 현재 페이지, 한 페이지당 보여줄 포스트 개수
def make_page_obj(item_list, page, num_of_post,):
    paginator = Paginator(item_list, num_of_post)
    try:
        page_obj = paginator.page(page)
        return page_obj, paginator
    except PageNotAnInteger:
        page = 1
        page_obj = paginator.page(page)
        return page_obj, paginator
    except EmptyPage:
        page = paginator.num_pages
        page_obj = paginator.page(page)
        return page_obj, paginator

templates/jobs/jobs-all.html
{% extends 'base.html' %}
{% block title %}과외서비스{% endblock %}
{% load static %}
{% block content %}
    <head>
        <link rel="stylesheet" href="{% static 'css/screens/search.css' %}">
    </head>
    


  <div id="header"></div>
  <script src="{%  static 'js/header.js' %}"></script>

  <section id="sec1">
    <div>
      <div id="serviceMain">온라인 
        <br>과외서비스</div> 
      <div id="service">영어, 중국어, 일본어부터 태국어, 베트남어 아랍어까지!<br>
        ‘다모여’는 다문화 가정의 경제적 활동을 지원합니다.<br>
        온라인 과외를 통해 다양한 언어를 배울 수 있는 기회를 제공합니다.
        </div>
    </div>
  </section>


  <sect id="sec2">
   <div id="box">
     <div id="box1">다양한 언어,</div>
     <div id="box2">관심 있으신가요?</div>
   </div>
    
    <div class="container">
        <div class ="imgBox"><img src="/static/image/Groupstar.png"></div>
        <div class="pictureBox">
            <h2>원어민에게 배운다고?</h2>
            <p>다모여에서는<br>
              원어민 다문화 가족 구성원에게<br>
              수업을 들을 수 있습니다.<br>
              <br><br>
              문법 중심의 암기 수업에서 벗어난,<br>
              '진짜'언어 수업을 만나보세요.</p>
              <br>
          </div>
        </div>

    <div class="container2">
      
      <div class="picture_Box">
          <h2>언제, 그리고 어디서나 </h2>
          <p>등교하기전 1시간<br>
            회사 점심시간 1시간<br>
            집가는 길에 전화 20분<br>
            퇴근 후 집에서 2시간<br>
            .<br>.<br>
            당신이 원하는 순간에, 어디서나<br>
          외국어 회화 공부를 할 수 있습니다.</p>
            <br>
          <P>여기, 다모여에서!</P>
        </div>

        <div class ="imgBox2"><img src="/static/image/Groupstar.png"></div>
      </div>

   

     <div id="box">
      <div id="box3">더 많은</div>
      <div id="box4">원어민 선생님을 </div>
      <div id="box5">만나보세요!</div>
      </div>
    
     
     
  <div class="containerBox"> 
    {% for teacher in teacher_list %}
        {% if forloop.counter == 1 %}
        <div id="cb1"><h1>{{teacher.name}}</h1>
          <p>{{teacher.language}}</p>
        </div>
        {% endif %}
        {% if forloop.counter == 2 %}
        <div id="cb2"><h1>{{teacher.name}}</h1>
          <p>{{teacher.language}}</p>
        </div>
        {% endif %}
        {% if forloop.counter == 3 %}
        <div id="cb3"><h1>{{teacher.name}}</h1>
          <p>{{teacher.language}}</p>
        </div>
        {% endif %}
        {% if forloop.counter == 4 %}
        <div id="cb4"><h1>{{teacher.name}}</h1>
          <p>{{teacher.language}}</p>
        </div>
        {% endif %}
        {% if forloop.counter == 5 %}
        <div id="cb5"><h1>{{teacher.name}}</h1>
          <p>{{teacher.language}}</p>
        </div>
        {% endif %}
        {% if forloop.counter == 6 %}
        <div id="cb6"><h1>{{teacher.name}}</h1>
          <p>{{teacher.language}}</p>
        </div>
        {% endif %}
        {% endfor %}
      </div>
      <button onclick="location.href='{% url 'jobs:teacher' %}'" id="btn">선생님 만나러가기 <img class="polygon"src="{% static 'image/Polygon 7.png'%}"></button>
    
  </section>
  
  <div class="girlcontainer">
    
    <div id="girl">

        <h2>선생님이 되어주세요!</h2>
        <p>주부도, 직장인도, 여자도, 남자도 누구나 선생님이 될 수 있습니다.<br>
        영상통화로 수업을 진행할 수 있어요.</p>
        <button class="girl-btn" onclick="location.href='{% url 'jobs:jobs_create' %}'">수업 등록하러가기</button>
    </div>
</div>


    
</section>




{% endblock %}

templates/jobs/jobs-detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
  <link rel="stylesheet" href="{% static 'css/screens/detail.css' %}">
</head>
<br>
<section id ="sec1">
  <div id="explain">
      <img class="img-profile" src="{{ teacher.image.url }}" alt="이미지">
    
      <div id="boxs">
        <div id="box1">{{teacher.name}} 선생님</div>
        <div id="box2">{{teacher.language}} 과외를 집에서 받을 수 있어요! </div>
        <div id="box3">{{teacher.language}}과외 경력 {%for i in info_list%}{{i}},{%endfor%}<br>
            {{teacher.nationality}} 출신 선생님<br>
            {{teacher.language}} 과외를 1시간 당 {{teacher.cost}}원에 받아보세요!</div>
            <img class="img-star" src="{% static 'image/starlogo.png'%}" width="80px" height="20px">
      
        <div class="rectangles">
        <div id ="rectangle">
          <div id="one">#{{teacher.language}}</div>
          <div id="four">#{{teacher.cost}}원</div>
          {% for group in group_list%}
            <div id="two">#{{group}}</div>
            {%endfor%}
        </div>

        <div id ="rectangle">
          {% for stu in stu_list%}
            <div id="tree">#{{stu}} 맞춤수업</div>
            {%endfor%}
        </div>
      </div>
      </div>
    </div>
  </div>
</section>


<section id="sec2">
    <div class="container">
        <div id ="img-container">
          <img class = "container-img"src="{% static 'image/container1.png' %}"  alt="c1" >
          <p>{{teacher.language}} 강의</p>
        </div>

      <div id ="img-container">
          <img class = "container-img" src="{% static 'image/container2.png' %}"  alt="c2" >
          <p>{%for i in stu_list%}{{i}} , {%endfor%} 맞춤</p>
      </div>

      <div id ="img-container">
        <img class = "container-img" src="{% static 'image/container3.png' %}"  alt="c3" >
        <p>교육 경력 {%for i in info_list%}{{i}}{%endfor%}</p>
      </div>  
    </div>    
</section>

<section id ="sec3">
<p>* 강사 정보</p>
    <div id ="total-information">
      <div class="information">
        <div>
          <div id="information1">국적</div>
          <div id="information2">{{teacher.nationality}}</div>
        </div>

        <div>
          <div id="information3">사용 가능 언어</div>
          <div id="information2">{{teacher.language}}</div>
        </div>

        <div>
          <div id="information1">특이사항</div>
          <div id="information4">{{teacher.feature}}</div>
        </div>


      <div id="informations">
        <div>
          <div id="gender">성별</div>
          <div id="women">{{teacher.gender}}성</div>
        </div>

        <div>
          <div id="time">수업시간</div>
          <div id="timetable">
          {% if time <= 3 %}
          {% for time in time_list %} 
            {{ time }}
          {% endfor %}
          {% else %}
          신청하기 버튼을 누르면 볼 수 있어요
          {%endif %}
          </div>
        </div>

    </div>
  </section>
  <button class="apply"onclick="location.href='{% url 'jobs:jobs_apply' teacher.id %}'">신청하기</button>

{%endblock%}

templates/jobs/jobs-teacher.html
{% extends 'base.html' %}
{% load static %}
{% block title %}정보{% endblock %}
{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'css/screens/jobs-teacher.css' %}">
    <!-- 최신순/스크랩순 정렬 jquery-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        var imagePath = "{% static 'image/filled_scrap.png' %}";
        var imagePaths = "{% static 'image/empty_scrap.png' %}";
        function sendRequest(bid, event) {
            var httpRequest = new XMLHttpRequest();
            httpRequest.onreadystatechange = function () {
                if (httpRequest.readyState === XMLHttpRequest.DONE && httpRequest.status === 200) {
                    console.log(httpRequest.responseText);
    
                    var json_data = JSON.parse(httpRequest.responseText);
                    if (json_data['message'] === 'ok') {
                        event.innerHTML = '<img class="item__star" src="' + imagePath + '" alt="Filled Scrap">';
                    }else{
                        event.innerHTML = '<img class="item__star" src="' + imagePaths + '" alt="Filled Scrap">';
                    }
                }
            };
            httpRequest.open("GET", "/jobs/teacher/scrap/" + bid, true);
            httpRequest.send();
        }
    </script>
    <style>
        .number-nav {
            width: 20%;
        }
    </style>
</head>

<body id="info-body">

    <div id="header"></div>
    <br><br>
    
    <div id="center">
        <div class="info-title">

                <div>
                    <h1>원어민 선생님을 만나보세요. </h1>
                    <p>영어, 중국어, 일본어부터 태국어, 베트남어 아랍어까지!<br>
                        '다모여'는 다문화 가정의 경제적 활동을 지원합니다.<br>
                        온라인 과외를 통해 다양한 언어를 배울 수 있는 기회를 제공합니다.
                    </p>
                </div>
        </div>
    </div>

    <main class="info-main">
        <div class="info-main-content">
                        <div class="item-container" id="item-container">
                            <div id="teacher_title___">원어민 과외 선생님</div>
                                <div class="item-container__column">
                                {% for teacher in teacher_list1 %}
                                    <div class="item">
                                        <div class="item__ct">{{teacher.nationality}}</div>
                                        <div class="item__ct">{{teacher.language}}</div>


                                        {% if request.user in teacher.scrap.all %} 
                                        <div onclick="sendRequest({{teacher.id}}, this)"><img class="item__star" src="{% static 'image/filled_scrap.png' %}"></div>
                                        {% else %}
                                        <div onclick="sendRequest({{teacher.id}}, this)"> <img class="item__star" src="{% static 'image/empty_scrap.png' %}"></div>
                                        {% endif %}

                                        <div class="item__topic">{{teacher.name}} 선생님</div>
                                        <div class="item__description">
                                            <div>{{teacher.feature}}</div>
                                    </div>
                                    <table class="item__table">
                                            <tr class="item__table-tr">
                                                    <td class="item__table-ctgory">이름</td>
                                                    <td class="item__table-ctgory-data">{{teacher.name}}</td>
                                            </tr>
                                            <tr class="item__table-tr">
                                                    <td class="item__table-ctgory">국적</td>
                                                    <td class="item__table-ctgory-data">{{teacher.nationality}}</td>
                                            </tr>
                                            <tr class="item__table-tr">
                                                    <td class="item__table-ctgory">언어</td>
                                                    <td class="item__table-ctgory-data">{{teacher.language}}</td>
                                            </tr>
                                            <tr class="item__table-tr">
                                                    <td class="item__table-ctgory">비용</td>
                                                    <td class="item__table-ctgory-data">시간당 {{teacher.cost}}원</td>
                                            </tr>
                                    </table>
                                    <button id="scrap-btn-6" class="item__more-btn" onclick="location.href='{% url 'jobs:teacher_detail' teacher.id %}'"> 자세히 보기</button>
                                </div>
                                {% endfor %}
                        </div>
                        <div class="item-container" id="item-container">
                            <div class="item-container__column">
                            {% for teacher in teacher_list2 %}
                                <div class="item">
                                    <div class="item__ct">{{teacher.nationality}}</div>
                                    <div class="item__ct">{{teacher.language}}</div>

                                    {% if request.user in teacher.scrap.all %} 
                                    <div onclick="sendRequest({{teacher.id}}, this)"><img class="item__star" src="{% static 'image/filled_scrap.png' %}"></div>
                                    {% else %}
                                    <div onclick="sendRequest({{teacher.id}}, this)"> <img class="item__star" src="{% static 'image/empty_scrap.png' %}"></div>
                                    {% endif %}

                                    <div class="item__topic">{{teacher.name}} 선생님</div>
                                    <div class="item__description">
                                        <div>{{teacher.feature}}</div>
                                </div>
                                <table class="item__table">
                                        <tr class="item__table-tr">
                                                <td class="item__table-ctgory">이름</td>
                                                <td class="item__table-ctgory-data">{{teacher.name}}</td>
                                        </tr>
                                        <tr class="item__table-tr">
                                                <td class="item__table-ctgory">국적</td>
                                                <td class="item__table-ctgory-data">{{teacher.nationality}}</td>
                                        </tr>
                                        <tr class="item__table-tr">
                                                <td class="item__table-ctgory">언어</td>
                                                <td class="item__table-ctgory-data">{{teacher.language}}</td>
                                        </tr>
                                        <tr class="item__table-tr">
                                                <td class="item__table-ctgory">비용</td>
                                                <td class="item__table-ctgory-data">시간당 {{teacher.cost}}원</td>
                                        </tr>
                                </table>
                                <button id="scrap-btn-6" class="item__more-btn" onclick="location.href='{% url 'jobs:teacher_detail' teacher.id %}'"> 자세히 보기</button>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="item-container" id="item-container">
                            <div class="item-container__column">
                            {% for teacher in teacher_list3 %}
                                <div class="item">
                                    <div class="item__ct">{{teacher.nationality}}</div>
                                    <div class="item__ct">{{teacher.language}}</div>


                                    {% if request.user in teacher.scrap.all %} 
                                    <div onclick="sendRequest({{teacher.id}}, this)"><img class="item__star" src="{% static 'image/filled_scrap.png' %}"></div>
                                    {% else %}
                                    <div onclick="sendRequest({{teacher.id}}, this)"> <img class="item__star" src="{% static 'image/empty_scrap.png' %}"></div>
                                    {% endif %}



                                    <div class="item__topic">{{teacher.name}} 선생님</div>
                                    <div class="item__description">
                                        <div>{{teacher.feature}}</div>
                                </div>
                                <table class="item__table">
                                        <tr class="item__table-tr">
                                                <td class="item__table-ctgory">이름</td>
                                                <td class="item__table-ctgory-data">{{teacher.name}}</td>
                                        </tr>
                                        <tr class="item__table-tr">
                                                <td class="item__table-ctgory">국적</td>
                                                <td class="item__table-ctgory-data">{{teacher.nationality}}</td>
                                        </tr>
                                        <tr class="item__table-tr">
                                                <td class="item__table-ctgory">언어</td>
                                                <td class="item__table-ctgory-data">{{teacher.language}}</td>
                                        </tr>
                                        <tr class="item__table-tr">
                                                <td class="item__table-ctgory">비용</td>
                                                <td class="item__table-ctgory-data">시간당 {{teacher.cost}}원</td>
                                        </tr>
                                </table>
                                <button id="scrap-btn-6" class="item__more-btn" onclick="location.href='{% url 'jobs:teacher_detail' teacher.id %}'"> 자세히 보기</button>
                            </div>
                            {% endfor %}
                        </div>
                        
        </div>

        <div class="information-footer">
            {% if page_obj.has_other_pages %}
                <ul class="number-nav">
                    {% if page_obj.has_previous %}
                        <li class="number-nav__list"><a href="?page={{page_obj.previous_page_number}}"><img id="left-btn" src="{% static 'image/left-btn.svg' %}"></a></li>
                    {% endif %}

                    {% for page in paginator.page_range %}
                        {% if page == page_obj.number %}
                            <li class="number-nav__list"><a href="?page={{page}}">{{ page }}</a></li>
                        {% else %}
                            <li class="number-nav__list" style="color:#977F6A;" ><a href="?page={{page}}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="number-nav__list"><a href="?page={{page_obj.next_page_number}}"><img id="right-btn" src="{% static 'image/left-btn.svg' %}"></a></li>
                    {% endif %}
                </ul>
            {% endif%}
        </div>

    </main>


{% endblock %}